/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    ErrorDialog: typeof import('./components/ErrorDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeacherDashboard: typeof import('./components/TeacherDashboard/TeacherDashboard.vue')['default']
  }
}
